name: auto_merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * fri'
    # cron表达式,每周五16点执行一次，actions任务时区为UTC时区。 


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
             #改为上游仓库分支名称
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      env:
          email: ${{ secrets.my_email }}
          name: ${{ secrets.my_name }}
      run : |
        git config --global user.email "${email}"
        git config --global user.name "${name}"
        #点击项目 Settings -> Secrets -> New Secrets 添加以下 2 个 Secrets
        #在secrets中设置添加变量名my_email，值为自己githib设置中的邮箱
        #在secrets中设置添加变量名my_name，值为自己githib设置中的用户名
    - name: Load upstream commits
      run: |
        git pull https://github.com/ACL4SSR/ACL4SSR.git --log --no-commit
        # 改为上游仓库地址
    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
                           #改为自己forks名称
        TZ: Asia/Shanghai
      run: git push origin $DOWNSTREAM_BRANCH
